-- Do NOT edit this file manually

require "message.opcode"

require "message.msg_1_session"
require "message.msg_2_player"
require "message.msg_3_hero"
require "message.msg_4_quest"
require "message.msg_5_chapter"
