-- Do NOT edit this file manually

cc.exports.Opcode  = {}
cc.exports.MsgName = {}

local Opcode  = Opcode
local MsgName = MsgName

Opcode.MSG_CS_PingRequest                     = 100;		MsgName[Opcode.MSG_CS_PingRequest]                     = "msg.PingRequest";
Opcode.MSG_SC_PingResponse                    = 101;		MsgName[Opcode.MSG_SC_PingResponse]                    = "msg.PingResponse";
Opcode.MSG_CS_LoginRequest                    = 102;		MsgName[Opcode.MSG_CS_LoginRequest]                    = "msg.LoginRequest";
Opcode.MSG_SC_LoginResponse                   = 103;		MsgName[Opcode.MSG_SC_LoginResponse]                   = "msg.LoginResponse";
Opcode.MSG_CS_EnterGameRequest                = 104;		MsgName[Opcode.MSG_CS_EnterGameRequest]                = "msg.EnterGameRequest";
Opcode.MSG_SC_EnterGameResponse               = 105;		MsgName[Opcode.MSG_SC_EnterGameResponse]               = "msg.EnterGameResponse";
Opcode.MSG_CS_PlayerDataRequest               = 200;		MsgName[Opcode.MSG_CS_PlayerDataRequest]               = "msg.PlayerDataRequest";
Opcode.MSG_SC_PlayerDataResponse              = 201;		MsgName[Opcode.MSG_SC_PlayerDataResponse]              = "msg.PlayerDataResponse";
Opcode.MSG_CS_GMCommandRequest                = 202;		MsgName[Opcode.MSG_CS_GMCommandRequest]                = "msg.GMCommandRequest";
Opcode.MSG_SC_GMCommandResponse               = 203;		MsgName[Opcode.MSG_SC_GMCommandResponse]               = "msg.GMCommandResponse";
Opcode.MSG_CS_UseItemRequest                  = 204;		MsgName[Opcode.MSG_CS_UseItemRequest]                  = "msg.UseItemRequest";
Opcode.MSG_SC_UseItemResponse                 = 205;		MsgName[Opcode.MSG_SC_UseItemResponse]                 = "msg.UseItemResponse";
Opcode.MSG_CS_MarketBuyRequest                = 206;		MsgName[Opcode.MSG_CS_MarketBuyRequest]                = "msg.MarketBuyRequest";
Opcode.MSG_SC_MarketBuyResponse               = 207;		MsgName[Opcode.MSG_SC_MarketBuyResponse]               = "msg.MarketBuyResponse";
Opcode.MSG_SC_ItemUpdate                      = 280;		MsgName[Opcode.MSG_SC_ItemUpdate]                      = "msg.ItemUpdate";
Opcode.MSG_SC_PlayerExpUpdate                 = 281;		MsgName[Opcode.MSG_SC_PlayerExpUpdate]                 = "msg.PlayerExpUpdate";
Opcode.MSG_SC_NoticeUpdate                    = 282;		MsgName[Opcode.MSG_SC_NoticeUpdate]                    = "msg.NoticeUpdate";
Opcode.MSG_CS_HeroLevelupRequest              = 300;		MsgName[Opcode.MSG_CS_HeroLevelupRequest]              = "msg.HeroLevelupRequest";
Opcode.MSG_SC_HeroLevelupResponse             = 301;		MsgName[Opcode.MSG_SC_HeroLevelupResponse]             = "msg.HeroLevelupResponse";
Opcode.MSG_CS_HeroRefineRequest               = 302;		MsgName[Opcode.MSG_CS_HeroRefineRequest]               = "msg.HeroRefineRequest";
Opcode.MSG_SC_HeroRefineResponse              = 303;		MsgName[Opcode.MSG_SC_HeroRefineResponse]              = "msg.HeroRefineResponse";
Opcode.MSG_SC_HeroInfoUpdateResponse          = 380;		MsgName[Opcode.MSG_SC_HeroInfoUpdateResponse]          = "msg.HeroInfoUpdateResponse";
Opcode.MSG_CS_QuestListRequest                = 400;		MsgName[Opcode.MSG_CS_QuestListRequest]                = "msg.QuestListRequest";
Opcode.MSG_SC_QuestListResponse               = 401;		MsgName[Opcode.MSG_SC_QuestListResponse]               = "msg.QuestListResponse";
Opcode.MSG_CS_QuestOpRequest                  = 402;		MsgName[Opcode.MSG_CS_QuestOpRequest]                  = "msg.QuestOpRequest";
Opcode.MSG_SC_QuestOpResponse                 = 403;		MsgName[Opcode.MSG_SC_QuestOpResponse]                 = "msg.QuestOpResponse";
Opcode.MSG_SC_QuestUpdate                     = 403;		MsgName[Opcode.MSG_SC_QuestUpdate]                     = "msg.QuestUpdate";
Opcode.MSG_CS_ChapterInfoRequest              = 500;		MsgName[Opcode.MSG_CS_ChapterInfoRequest]              = "msg.ChapterInfoRequest";
Opcode.MSG_SC_ChapterInfoResponse             = 501;		MsgName[Opcode.MSG_SC_ChapterInfoResponse]             = "msg.ChapterInfoResponse";
Opcode.MSG_CS_ChapterFightingRequest          = 502;		MsgName[Opcode.MSG_CS_ChapterFightingRequest]          = "msg.ChapterFightingRequest";
Opcode.MSG_SC_ChapterFightingResponse         = 503;		MsgName[Opcode.MSG_SC_ChapterFightingResponse]         = "msg.ChapterFightingResponse";
Opcode.MSG_CS_ChapterRewardsRequest           = 504;		MsgName[Opcode.MSG_CS_ChapterRewardsRequest]           = "msg.ChapterRewardsRequest";
Opcode.MSG_SC_ChapterRewardsResponse          = 505;		MsgName[Opcode.MSG_SC_ChapterRewardsResponse]          = "msg.ChapterRewardsResponse";
Opcode.MSG_CS_ChapterLootRequest              = 506;		MsgName[Opcode.MSG_CS_ChapterLootRequest]              = "msg.ChapterLootRequest";
Opcode.MSG_SC_ChapterLootResponse             = 507;		MsgName[Opcode.MSG_SC_ChapterLootResponse]             = "msg.ChapterLootResponse";
