local data = 
{
	[1] = {
		id = 4001,
		name = "元宝",
		icon = "icon/item/item_4001.png",
		desc = "玩家资源",
		qulity = 1,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 0,
		param2 = 0,
		param3 = { 0, 0, },
		param4 = "",
	},

	[2] = {
		id = 4002,
		name = "黄金",
		icon = "icon/item/item_4002.png",
		desc = "玩家资源",
		qulity = 1,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 0,
		param2 = 0,
		param3 = { 0, },
		param4 = "",
	},

	[3] = {
		id = 4103,
		name = "英雄经验丹",
		icon = "icon/item/item_4103.png",
		desc = "desc_111",
		qulity = 2,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 0,
		param2 = 0,
		param3 = { 0, },
		param4 = "",
	},

	[4] = {
		id = 4104,
		name = "VIP经验丹",
		icon = "icon/item/item_4104.png",
		desc = "desc_222",
		qulity = 2,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 0,
		param2 = 0,
		param3 = { 0, },
		param4 = "",
	},

	[5] = {
		id = 4105,
		name = "黄金大礼包",
		icon = "icon/item/item_4105.png",
		desc = "desc_333",
		qulity = 3,
		type_p = 1,
		type_s = 0,
		use_type = 1,
		param1 = 4001,
		param2 = 999,
		param3 = { 0, },
		param4 = "",
	},

	[6] = {
		id = 4106,
		name = "印度神油",
		icon = "icon/item/item_4106.png",
		desc = "",
		qulity = 3,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 0,
		param2 = 0,
		param3 = { 0, },
		param4 = "",
	},

	[7] = {
		id = 4107,
		name = "诛仙令",
		icon = "icon/item/item_4107.png",
		desc = "",
		qulity = 4,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 0,
		param2 = 0,
		param3 = { 0, },
		param4 = "",
	},

	[8] = {
		id = 4108,
		name = "兑换钥匙",
		icon = "icon/item/item_4108.png",
		desc = "",
		qulity = 4,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 0,
		param2 = 0,
		param3 = { 0, },
		param4 = "",
	},

	[9] = {
		id = 4109,
		name = "请假条",
		icon = "icon/item/item_4109.png",
		desc = "",
		qulity = 5,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 0,
		param2 = 0,
		param3 = { 0, },
		param4 = "",
	},

	[10] = {
		id = 4110,
		name = "减免券",
		icon = "icon/item/item_4110.png",
		desc = "",
		qulity = 5,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 0,
		param2 = 0,
		param3 = { 0, },
		param4 = "",
	},

	[11] = {
		id = 4111,
		name = "精炼符",
		icon = "icon/item/item_4111.png",
		desc = "",
		qulity = 5,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 0,
		param2 = 0,
		param3 = { 0, },
		param4 = "",
	},

	[12] = {
		id = 4112,
		name = "超级精炼符",
		icon = "icon/item/item_4112.png",
		desc = "",
		qulity = 5,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 0,
		param2 = 0,
		param3 = { 0, },
		param4 = "",
	},

	[13] = {
		id = 4113,
		name = "经验丹",
		icon = "icon/item/item_4113.png",
		desc = "",
		qulity = 5,
		type_p = 1,
		type_s = 0,
		use_type = 0,
		param1 = 1000,
		param2 = 0,
		param3 = { 0, },
		param4 = "",
	},

}

return data
